version: '3.8'

services:

  wordpress:
    image: wordpress
    restart: always
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: mysql:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: password
      WORDPRESS_DB_NAME: wordpressdb
    volumes:
      - wordpress:/var/www/html
      #- ./wordpress:/var/www/html
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: wordpressdb
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: password
      MYSQL_RANDOM_ROOT_PASSWORD: '0'
    volumes:
      - mysql:/var/lib/mysql
      #- ./mysql:/var/lib/mysql
    ports:
      - "3366:3306"

volumes:
  wordpress:
  mysql:
  
networks:
    wordpress_network:
        driver: bridge